### ISSUE TITLE
History entry on every update

### ISSUE THREAD

**Issue by gladky** [cmsdaq/daqview-react#27] opened 2017-05-24 14:56 UTC
Oliver reported that new DAQView is creating history entry every 2 seconds. The history file is right now ~160 Mb. We need to disable it as it's useless.

**Comment by mvougiou** [comment] 2017-05-25 08:41
Hi,

This is a by-product of how the live, re-usable URL in the address bar 
is implemented. It is implemented by pushing the current URL (with 
parameters) into the window's history at each update. It's the same 
implementation as in the online RunInfoTimeline if I remember correctly. 
So you would probably see the same effect with that application as well.

Rather than disabling the window history pushes (which will break the 
live URL feature), I would advise to look for a function or parameter so 
that the latest history entry is overwritten, instead. Of course there 
is no guarantee this entry will be the previous daqview URL, it could be 
any previous address which was inserted in the address bar. Outside the 
control room, for personal computers, this may not be desired...

Cheers,

Michail

**Comment by Phil2812** [comment] 2017-05-25 13:46
Hello,

yes, the RunInfoTimeline uses the same functionality and is most likely affected by the same problem. The new URL is not actually pushed, but replaced (history.replaceState is used instead of history.pushState), so the window's history only shows one item. However, the cause of the problem is mentioned here: https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method
"Note that this doesn't prevent the creation of a new entry in the global browser history." meaning that while replaceState actually does replace the history for the current window, an entry of the previous URL will still be kept in the global browser history.

I am not aware of any alternatives that would not cause this problem, since window.location.replace(URL) also affects the global history in Firefox and opens the supplied URL, causing an unwanted page reload. Using window.location.hash to store the parameters in the form URL#parameters will also cause a new history entry in Firefox and would also require changes to how parameters are parsed.

Cheers,
Philipp

**Comment by Phil2812** [comment] 2017-10-06 14:50
Fixed in 5201c3b9d6e829193c4f5f17b8ba17536024acae

**Closed by Phil2812** 2017-10-06 14:50 UTC
